version: '3.1'
services:
    php-app:
        build:
            context: ../
        container_name: php-app
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html
        environment:
            MYSQL_HOST: mysql
            MYSQL_NAME: energy-monitor
            MYSQL_USER: energy-monitor
            MYSQL_PASS: 123

    mysql:
        image: mysql:5.7
        container_name: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
        volumes:
            - ./../database/create.sql:/docker-entrypoint-initdb.d/schema.sql
            - ./mysql/data:/var/lib/mysql
        ports:
            - "8306:3306"
        env_file: ./mysql/mysql.env

    swagger:
        image: swaggerapi/swagger-ui
        container_name: swagger
        ports:
            - "8082:8080"
        environment:
            API_URL: "http://localhost:8080/api/v1/openapi"

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - "8081:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
